name: nf-str
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - htslib
  - bcftools
  - samtools
  - scipy
  - scikit-learn
  - pysam
  - numpy
  - polars
  - plotnine
  - pip
  - pip:
    - ATaRVa>=0.3.0