name: nf-str
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - htslib
  - bcftools
  - samtools
  - minimap2
  - cyvcf2
  - scipy
  - scikit-learn
  - pysam
  - numpy
  - polars
  - plotnine